### ISSUE TITLE
Offensive/Spam

### ISSUE THREAD

**Issue by duttashi** [scalingexcellence/scrapybook#16]

**Comment by lookfwd** [comment]
Hello, from the browser, outside the VM,  it should be:

http://localhost:9312/properties/property_000000.html

**Comment by duttashi** [comment]
thanks, but it still does not work. Error message: "This site can’t be reached
localhost refused to connect. ERR_CONNECTION_REFUSED"

**Comment by lookfwd** [comment]
Ok, it seems like we will need more info. What operating system are you using? Did the VM start with no errors? Your browser is outside the VM, right? Inside the VM `scrapy crawl` and `scrapy shell` work fine as described in the book (maybe a bit later in the chapter), but outside the VM you just can't access the page, is this correct?

In general see this video, here at this point: https://youtu.be/r84-dsIRFI8?t=745 . This is the starting process and it tells you at the end to ping `web` etc. Does this work for you or it gives you an error?

**Comment by duttashi** [comment]
Ahh now I realize that you have made this a whole lot complicated which in my opinion is not required (I could be wrong too). One can easily write and execute a crawler without the need of a VM on a windows based OS. In fact, I have done this successfully on my computer. I also understand that some folks would not want to tinker with there environment variables. Anyway, I am not going to go through the tedious process of VM installation and scraping using it.  Thanks for your time.

**Comment by lookfwd** [comment]
> One can easily write and execute a crawler without the need of a VM on a windows based OS. In fact, I have done this successfully on my computer.

Nice! Could you summarise how you did it for the benefit of others? I guess you had to go through [this](http://stackoverflow.com/questions/5267092/how-do-i-install-pyopenssl-on-windows-7-64-bit) right?

That said, writing a book that supports Windows without a VM, would require me to rewrite every single command on the book with backslashes taking care of all the Win incompatibilities and Scrapy Win bugs (typically related to paths). I know this path is a pain because I followed it in one of the first version of the book and one of the reviewers told-me-off and suggested I just use a VM and that people who are serious on getting professional with Python/Scrapy would only benefit from such environment rather than wasting tons of time with various Win peculiarities and then have to re-learn everything as soon as they release to cloud servers. He was quite convincing.

In any case, as soon as you get to Chapter 9 and 11 one can certainly see examples that interface with many software packages and they're reason enough to provide a VM instead of supporting people on installing them on every platform imaginable.

I believe that since you've gone through the pains of installing Scrapy on Win, you will likely not find that "tedious" the "process of VM installation". I highly encourage it and will change your life. That said, if you don't want to do that, send me an e-mail and we will find a trivial way to setup the python properties website on your computer. Hint: It's a [Twisted](https://twistedmatrix.com/trac/) application - exactly like Scrapy - and it's [here](https://github.com/scalingexcellence/scrapybook-docker-web).

**Comment by duttashi** [comment]
" I guess you had to go through this right?", No. I did not go through those steps you have higlighted!. 

"...writing a book that supports Windows without a VM, would require me to rewrite every single command on the book with backslashes taking care of all the Win incompatibilities and Scrapy Win bugs (typically related to paths)...". It has taken me less than 10 steps including its configuration with an IDE on a windows machine.

The steps I undertook to install working instantiation of Scrapy on a windows OS have been elaborated on my blog post [here](https://edumine.wordpress.com/2016/10/31/scrapy-on-windows-setup/). Interested readers can take a look.  I have also included in the post on its configuration with PyCharm IDE.

"That said, if you don't want to do that, send me an e-mail and we will find a trivial way to setup the Python properties website on your computer", laughs, guess what, I'm giving you a working instantiation of Scrapy on Windows OS (refer above to my blog post) without your cumbersome procedure of VM installation.

**Comment by lookfwd** [comment]
Nice blog post. I highly encourage the process from [here](https://edumine.wordpress.com/2016/10/31/scrapy-on-windows-setup/) for driven Windows hackers who don't have a VM as an option. It requires installation of Microsoft Visual C++ and several other packages with Windows installers and `pip`. One would also have to install book's web server from [here](https://github.com/scalingexcellence/scrapybook-docker-web), install MySQL, Redis, Spark, ElasticSearch and scrapyd if they plan to go beyond Chapter 8 and fix anything that doesn't work. Please also confirm that pyOpenSSL is functional (might require you to install OpenSSL).

By following the above path one becomes an eccentric Python/Scrapy developer who will have to go through extra pain to make things work on Win and then will have to do do the same on an easier way if (s)he plans to deploy on Linux VMs on amazon or any other cloud provider. I find the profile of someone who is quite comfortable using Windows' command prompt to install Python packages but needs to setup PyCharm to avoid using Windows' command prompt to run scrapy, or finds it easier to install MS VC++ than VirtualBox somewhat contradicting but I can see that it's an interesting academic exercise to make a point.

Once again - I won't be able to provide any support for this workflow and good luck finding versions of software compatible with the book 2 years down the line.

**Comment by duttashi** [comment]
"Be aware that by following the above path one becomes an eccentric Python/Scrapy developer who will have to go through extra pain to make things work on Win....", I reiterate there is no extra pain involved in the steps that I have documented, rather its tormenting to follow a mindless activity of VM installation on Win according to your perceived approach. 

" install MySQL, Redis, Spark, ElasticSearch and scrapyd if they plan to go beyond Chapter 8 and fix anything that doesn't work e.g. stuff related to paths", one of the approaches which I have noticed among novice writers is to wrap a simple concept in absurdly insane concoction leaving the readers to gasp in awe (which often is the writer's intention) but actually it only adds to "confusion" and nothing else. This is why, peer-reviewed books are more acclaimed and easier to read and understand because  they refrain from the whims and fancies of a sole author.

"Once again - I won't be able to provide any support for this workflow and good luck finding versions of software compatible with the book 2 years down the line." laughs hard, I dont need your support. I have already figured out an easier approach to suit my needs. I'm not reading this book any more. It is not worth my time.

Knowing a language is not enough! Its pertinent for a good writer especially a technical content writer (emphasis added) to be able to provide a justified and a balanced view point which unfortunately is a scarcity to be found these days especially when one comes across books such as these where the sole purpose seems to channel the learning process into oblivion!

Good luck
