### ISSUE TITLE
can't boot VMMachine with vagrant up --no-parallel

### ISSUE THREAD

**Issue by fengben** [scalingexcellence/scrapybook#42]
i git clone the code ,and boot the VM with vagrant up --no-parallel,than i get stack,the below is cmd message.
$ vagrant up --no-parallel
Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
==> web: Docker host is required. One will be created if necessary...

Your help is much appreciated.

**Comment by lookfwd** [comment]
hello, in which timezone are you?

**Comment by fengben** [comment]
GMT+8 thank you

**Comment by lookfwd** [comment]
Great we're on the same - let's setup a teamviewer session - should be easy to fix. You can send me an e-mail with your teamviewer id at lookfwd@gmail.com

**Comment by labdmitriy** [comment]
Hello,
Have you resolved the issue? I have the same problem.

**Comment by lookfwd** [comment]
@labdmitriy, did it work?

**Comment by fengben** [comment]
sorry , i forgot it, i give up the windows and choice another new Ubuntu to do it,and it words. Thanks a lot .

**Comment by fengben** [comment]
But i  still don't know why, whatever , i find another way. 0.0

**Comment by labdmitriy** [comment]
Hello, 

I am new in Docker and Vagrant, but I have resolved it by changing force_vm_host setting to false (lowercase), to avoid the error mentioned in this issue, and also to avoid this ruby warning (https://blog.bigbinary.com/2017/06/19/ruby-2-4-has-depecated-constants-true-false-and-nil.html).
Also if you install virtualbox and run Vagrantfile as is, it will also work, but the description in the book is about running native docker containers without VM on Linux (I'm using Ubuntu 14.04) and we didn't install virtual box for Linux in the corresponding chapter as I understand, so maybe this is a little bit confusing.

After changing this parameter, all is working fine, though I have warnings like in another issue (Provisioners will not be run since container doesn't support SSH).

Thank you.

**Comment by iMackson** [comment]
Thanks, @labdmitriy, your solution has worked for me. Thanks a lot @lookfwd for this beautiful work.
