### ISSUE TITLE
ERROR:   C:/Users/USER/Desktop/scrapybook/Vagrantfile:4: warning: constant ::TRUE is deprecated

### ISSUE THREAD

**Issue by andy940255** [scalingexcellence/scrapybook#44]
it is my ....   problem
I am NOT good at English,sorry
I reference the first video in this (http://scrapybook.com/)
but something wrong...
I am a Beginners for this,I will thank you for your advice.
------------------------------------------------------------------------------------------------
Microsoft Windows [版本 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\USER>Desktop
'Desktop' 不是內部或外部命令、可執行的程式或批次檔。

C:\Users\USER>cd Desktop

C:\Users\USER\Desktop>git clone https://github.com/scalingexcellence/scrapybook.
git
Cloning into 'scrapybook'...
remote: Counting objects: 1218, done.
emote: Total 1218 (delta 0), reused 0 (delta 0), pack-reused 1218Receiving objec
Receiving objects: 100% (1218/1218), 621.32 KiB | 101.00 KiB/s, done.

Resolving deltas: 100% (599/599), done.
Checking connectivity... done.

C:\Users\USER\Desktop>cd scrapybook

C:\Users\USER\Desktop\scrapybook>vagrant up --no-parallel
# C:/Users/USER/Desktop/scrapybook/Vagrantfile:4: warning: constant ::TRUE is depr
ecated   (I don't know why it appeared)
Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
==> web: Docker host is required. One will be created if necessary...

it stop here

**Comment by peterceyu** [comment]
I am having essentially same problem. I think the problem is with incompatible character encoding as can be seen in below print outs. And after spending hours on this, I don't know how to solve this issue. Help!
![scrapy error](https://user-images.githubusercontent.com/22188961/33526159-1b8d4e94-d880-11e7-86dc-c7eab7d84739.png)


-------------------------------------------------
web: docker-provider: importing base box 'lookfwd/scrapybook'...
C:\HashiCorp\Vagrant\embedded\gems\gems\childprocess-0.6.3\lib\childprocess\windows\process_builder.rb:43:in 'join': incompatible character encodings: CP949 and UTF-8 (Encoding::CompatibilityError)

**Comment by lookfwd** [comment]
This is the right approach with Windows. The username is non-utf-8 and the relevant discussion is [here](https://github.com/hashicorp/vagrant/issues/2113).

**Comment by lookfwd** [comment]
They follow-up [here](https://github.com/hashicorp/vagrant/issues/4966). Essentially they say to not install vagrant etc. on directories that have non-english characters if I understand correctly.

**Comment by leon0707** [comment]
/.../scrapybook/Vagrantfile:4: warning: constant ::TRUE is deprecated

Warning will disappear if replace TRUE with true
